[project]
name = "odoo-addons-sygel-technology-sy-account-financial-reporting"
version = "18.0.20251003.0"
dependencies = [
    "odoo-addon-account_invoice_report_hide_delivery_address==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
